Encoding Techniques

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "!"

In [3]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [6]:
data = pd.DataFrame({
  'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red'],
  'Size' : ['S', "M", "L", "M", "XL"],
  'Gender' : ['Male', 'Female', 'Female', 'Male', 'Male'],
  'Purchased' :['Yes', 'No', 'Yes', 'No', 'Yes']
})
data

   Color Size  Gender Purchased
0    Red    S    Male       Yes
1   Blue    M  Female        No
2  Green    L  Female       Yes
3   Blue    M    Male        No
4    Red   XL    Male       Yes

In [10]:
# 1. Label Encoding for 'Color'
labe1_encoder = LabelEncoder()
data['Color_Label'] = labe1_encoder.fit_transform(data['Color'])
data[["Color", 'Color_Label']]

   Color  Color_Label
0    Red            2
1   Blue            0
2  Green            1
3   Blue            0
4    Red            2

In [14]:
# Apply OneHotEncoding
onehot_encoder = OneHotEncoder()
color_encoded = onehot_encoder.fit_transform(data [['Gender']])

# Convert sparse matrix to array 
color_df = pd.DataFrame(color_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['Gender']))

color_df

   Gender_Female  Gender_Male
0            0.0          1.0
1            1.0          0.0
2            1.0          0.0
3            0.0          1.0
4            0.0          1.0

In [18]:
#Oridinal Encoding
size_order = [['S', 'M', 'L', 'XL']]
Ordinal_ncoder = OrdinalEncoder(categories=size_order)
data['Size_ordinal'] = Ordinal_ncoder.fit_transform(data[['Size']])
data[['Size', 'Size_ordinal']]

  Size  Size_ordinal
0    S           0.0
1    M           1.0
2    L           2.0
3    M           1.0
4   XL           3.0

In [23]:
#  Binary Endcoding  for 'Purchased
data['Purchased_Binary'] = data['Purchased'].map({'Yes':1 , 'No': 0})
data[['Purchased', 'Purchased_Binary']]

  Purchased  Purchased_Binary
0       Yes                 1
1        No                 0
2       Yes                 1
3        No                 0
4       Yes                 1

In [24]:
# Final Encoded Data
encoded_data = pd.concat([data.drop(columns=['Color', 'Size', 'Gender', 'Purchased']), color_df], axis=1)
encoded_data

   Color_Label  Size_ordinal  Purchased_Binary  Gender_Female  Gender_Male
0            2           0.0                 1            0.0          1.0
1            0           1.0                 0            1.0          0.0
2            1           2.0                 1            1.0          0.0
3            0           1.0                 0            0.0          1.0
4            2           3.0                 1            0.0          1.0